apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
   lable-name: "t1"

spec:
  containers:
  - name: container1
    image: alihaamed17/os2-task:latest
    resources:
     limits:
      memory: "512Mi"
      cpu: "1"